### ISSUE TITLE
添加潜在的403错误警告

### ISSUE THREAD

**Issue by DazeCake** [xz454867105/chaoxing#23]
在本地跑的没问题，挂服务器上一直报` json.decoder.JSONDecodeError`
看了下代码，发现是登陆的时候报403了，希望可以加个提示啥的
定位位置：`src/user/getUser.py, line 68, in login
    result = resp.json()`

**Comment by xz454867105** [comment]
感谢反馈，我怀疑是Linux中Python的默认编码问题。我刚刚给文件头加上了编码限制，你可以重新拉取代码再试试
